# VC5 L2DSR Load Balancer config
---
learn: 80
multicast: 224.0.0.1:9999
rhi:
  as_number: 65304
  peers:
    - 10.10.100.3
    - 10.10.100.4

services:

  # webservers on 2 VIPs, standard HTTP and HTTPs ports
  - name: nginx
    description: NGINX webserver
    address:
      - 192.168.101.1
      - 192.168.101.2
    servers:
      - 10.10.100.120
      - 10.10.100.121
      - 10.10.100.122
      - 10.10.100.123
      - 10.10.100.124
      - 10.10.100.125
    host: foo.example.com
    path: /alive
    policy: webserver
      http:
      https:

  # iperf server with port/healthcheck and server list declared separately
  - name: iperf
    description: bandwidth test
    address: 192.168.101.3
    servers: iperf
    policy: iperf

policy:
  iperf:
    5001:
      type: syn

servers:
  iperf:
    - 10.10.100.130
    - 10.10.100.131
