# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s4f0:
      accept-ra: no
      link-local: []
    enp3s4f1:
      accept-ra: no
      link-local: []      
      
  bonds:
    bond0:
      dhcp4: yes
      interfaces: [enp3s4f0, enp3s4f1]
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        transmit-hash-policy: layer2+3
        mii-monitor-interval: 100
      accept-ra: no
      link-local: []

  vlans:
    vlan2:
      id: 2
      link: bond0
      addresses: [192.168.2.200/24]
      accept-ra: no
      link-local: []
    vlan3:
      id: 3
      link: bond0
      addresses: [192.168.3.200/24]
      accept-ra: no
      link-local: []
    vlan4:
      id: 4
      link: bond0
      addresses: [192.168.4.200/24]
      accept-ra: no
      link-local: []
    vlan5:
      id: 5
      link: bond0
      addresses: [192.168.5.200/24]
      accept-ra: no
      link-local: []

# enable if needed for native mode
# remove dhcp from bond0
#  bridges:
#    br0:
#      interfaces: [bond0]
#      parameters:
#        stp: no
#      accept-ra: no
#      link-local: []      
#      dhcp4: yes
