---

learn: 10
multicast: 224.0.0.1:9999
rhi:
  as_number: 65000
  peers:
    - 10.10.100.3
    - 10.10.100.4
  communities:
    # - 12345:678

services:

  - name: nginx
    description: NGINX webserver
    virtual:
      - 192.168.101.1
    servers:
      - 10.10.100.130
      - 10.10.100.131
    host: foo.example.com
    path: /
    need: 1
    policy:
      http:

vlans:
  # 101: 10.10.101.0/24
  # 102: 10.10.102.0/24  
