# VC5 L2DSR Load Balancer config
---

# This *might* be out of data and need checking/updating

# 'rhi' (route health injection) specifies BGP peers and ASN to use to avertise VIPs 
# 'learn' specifies how long to wait in seconds before adverising rhi to peers
# 'multicast' is the address to use to announce/listen for flow state information
# in a cluster. currently each flow gets announced every ~60s

learn: 5
multicast: 224.0.0.1:9999
rhi:
  hold_time: 5
  as_number: 65304
  peers:
    - 10.10.100.3
    - 10.10.100.4
  communities:
    # - 12345:678

services:

  # webservers on 2 VIPs, standard HTTP and HTTPs ports with standard checks
  # At least 3 servers need to be alive for the service/vip to be advertised
  # Setting the 'host' and 'path' options will cause http/http healthchecks
  # to use those values for the Host header and resource path that is queried
  - name: nginx
    description: NGINX webserver
    virtual:
      - 192.168.101.1
      - 192.168.101.2
    servers:
      - 10.10.100.120
      - 10.10.100.121
      - 10.10.100.122
      - 10.10.100.123
      - 10.10.100.124
      - 10.10.100.125
    host: foo.example.com
    path: /alive
    need: 3
    policy:
      http:
      https:

  # iperf server with port/healthcheck and server list declared separately
  # If 'need' is not specified it will default to 1 by the Perl script
  # If need be, you can explicitly set it to 0. Use "sticky" selection -
  # only considers Layer 3 data when when selecting a backend.
  - name: iperf
    description: bandwidth test
    virtual: 192.168.101.3
    sticky: true
    servers: iperf
    policy: iperf

  # BIND DNS server - both TCP and UDP services will be created.
  # Healthchecks which look for a response to a CHAOS TXT query for
  # the version.bind record will be to each service
  - name: bind
    description: BIND DNS server
    virtual: 192.168.101.4
    servers: bind
    path: /inservice
    policy:
      domain:

# labelled sets of policies as referred to above
policy:
  iperf:
    5001:
      checks:
        - type: syn

servers:
  iperf:
    - 10.10.100.130
    - 10.10.100.131
  bind:
    - 10.10.100.140
    - 10.10.100.141
